language: generic
osx_image: xcode9.3
before_install:
  - sudo gem install cocoapods
  - brew update && brew bundle
  - buck --version
  - java -version
script: 
  - jdk_switcher use oraclejdk8
  - make test
