language: generic
os: osx
osx_image: xcode9.3
before_install:
  - brew bundle
  - bundle install
  - buck --version
  - java -version
env:
  - TERM=dumb
script: 
  - make targets
  - make build
  - make test
  - make project
  - make xcode_tests
