version: 2
jobs:
  build-and-test:
    macos:
      xcode: "12.2.0"
    environment:
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            gem install bundler:1.17.3
            bundle install
            java -version

      - run:
          name: Build and run tests
          command: make ci

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
